### ISSUE TITLE
Definição de requisitos

### ISSUE THREAD

**Issue by gricar** [gricar/ContactsManager-API#1]
**Event Storming**
- [x] Identificação de eventos de domínio relevantes.
- [x] Definição de comandos e políticas.
- [x] Implementação de modelos de leitura para consultas.

**Comment by adolphomorais** [comment]
**Descrição Escopo Projeto**

_Cadastro de contatos:_ permitir o cadastro de novos contatos, incluindo nome, telefone e e-mail. Associe cada contato a um DDD correspondente à região.
_Consulta de contatos:_ implementar uma funcionalidade para consultar e visualizar os contatos cadastrados, os quais podem ser filtrados pelo DDD da região.
_Atualização e exclusão:_ possibilitar a atualização e exclusão de contatos previamente cadastrados.

**(Domínios e atributos)**
Contato
 - guid
   guid gerado como chave do contato criado no cadastro
 - nome
   informação obrigatória
 - codigoddd
   informação obrigatória
   formatação (2 dígitos numéricos)
 - telefone
   informação obrigatória
   formatação (9 dígitos numéricos obrigatório)
 - email
   informação opcional

Regiao
 - codigoddd
   informação obrigatória
   2 dígitos numéricos 
 - nome
   informação obrigatória
 - lista ddd e nomes permitidos
    Centro-Oeste
    61,62,64,65,66,67
    Nordeste
    71,73,74,75,77,79,81,82,83,84,85,86,87,88,89,98,99
    Norte
    63,68,69,91,92,93,94,95,96,97
    Sudeste
    11,12,13,14,15,16,17,18,19,21,22,24,27,28,31,32,33,34,35,37,38
    Sul
    41,42,43,44,45,46,47,48,49,51,53,54,55
    
**(Eventos)**
Usuário --cadastra --> Contato
 - atributos obrigatórios (nome, codigoddd, telefone)
 - atributos opcionais (email)
 - validar se codigoDDD existe em alguma região cadastrada
 - não permitir cadastro duplicado com a mesma chave unica codigoddd + telefone
 - não necessário realizar validação de formatação de email
 - gerar guid do cadastro do realizado

Usuário --informa  --> Regiao           --> paraconsultar --> Contato
Usuário --informa  --> codigoDDD   --> paraconsultar --> Contato
Usuário --informa  --> Nome      	   --> paraconsultar --> Contato
Usuário --informa  --> guid      	   --> paraconsultar --> Contato
 - filtro de consulta (regiao): trazer todos os contatos vinculados aos codigoddd da região informada
 - filtro de consulta (codigoddd): trazer todos os contatos vinculados ao codigoddd informado
 - filtro de consulta (nome contato): trazer todos os contatos com o nome informado
 - filtro de consulta (guid): trazer o contato da guid consultada
 - pelo menos um dos filtros é obrigatório
 - é permitido combinar todos os filtros disponíveis de consulta
 - se informado codigoDDD e região nos filtros, validar se o codigoDDD pertence a região informada

Usuário --exclui --> Contato
 - usuário solicita exclusão pelo guid
 - validar se a guid existe cadastro associado para exclusão
 - usuário solicita exclusão pelos campos ddd + telefone 
 - validar se a chave codigoDDD + telefone existe cadastro associado para exclusão

Usuário --atualiza --> Contato
 - usuário atualiza dados do cliente (códigoDDD, telefone, nome, email) pelo guid do contato
 - validar se a guid existe cadastro associado para alteração dos dados
 - não permitir cadastro duplicado com a mesma chave unica codigoddd + telefone
